name=DS1307-mario
version=1.0
author=mario-paul
maintainer=mario
sentence=DS1307RTC
paragraph=DS1307RTC rotina de teste de uso do DS1307-mario
category=Sensors
url=http://playground.arduino.cc/
architectures=*
